#!/usr/bin/env bash
# One-shot installer for repo-local git hooks (stage 104.2).
#
# Installs hooks into .git/hooks/ with the project's workflow-discipline
# policy. Operator-controlled (run manually after clone); not auto-installed.
#
# Usage:
#   ./scripts/install_git_hooks.sh

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_DIR="${ROOT}/.git/hooks"
if [ ! -d "$HOOK_DIR" ]; then
  echo "ERROR: .git/hooks/ not found — are you in the repo root?" >&2
  exit 1
fi

COMMIT_MSG_HOOK="${HOOK_DIR}/commit-msg"
PRE_COMMIT_HOOK="${HOOK_DIR}/pre-commit"
PRE_PUSH_HOOK="${HOOK_DIR}/pre-push"
VERSIONED_PRE_COMMIT="$ROOT/scripts/git-hooks/pre-commit"
if [ ! -r "$VERSIONED_PRE_COMMIT" ]; then
  echo "ERROR: versioned pre-commit hook not found: $VERSIONED_PRE_COMMIT" >&2
  exit 1
fi

# ── commit-msg hook: enforces 'Stage N: ...' + AssumptionLog section ───────

cat > "$COMMIT_MSG_HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh (stage 104.2).
# Blocks commits with 'Stage N:' prefix if AssumptionLog.md has no '## Этап N' section.

set -eu

MSG_FILE="$1"
FIRST_LINE=$(head -1 "$MSG_FILE" 2>/dev/null || echo "")

# Extract N from "Stage N:" or "Stage N." prefix (case-insensitive).
N=$(echo "$FIRST_LINE" | grep -oiE '^stage [0-9]+[.:]' | grep -oE '[0-9]+' | head -1 || true)
if [ -z "$N" ]; then
  # Not a stage commit — no enforcement
  exit 0
fi

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

# 1. AssumptionLog section for stage N (accept 'Этап N', 'Этап N.', 'Этап N–M')
if ! grep -qE "^## Этап ${N}([^0-9]|\$)" AssumptionLog.md 2>/dev/null; then
  echo "ERROR: commit message is 'Stage ${N}: ...' but AssumptionLog.md has no '## Этап ${N}' section." >&2
  echo "CLAUDE.md §6 requires an AssumptionLog entry as completion criterion." >&2
  echo "" >&2
  echo "Either:" >&2
  echo "  1. Add '## Этап ${N}. <title>' section to AssumptionLog.md and re-stage it" >&2
  echo "  2. Or adjust commit message if this is not a stage commit" >&2
  echo "  3. Or bypass with 'git commit --no-verify' (not recommended)" >&2
  exit 1
fi

# 2. Non-blocking warnings from workflow-check
if [ -x scripts/review_workflow_check.sh ]; then
  WC_OUT=$(./scripts/review_workflow_check.sh "${N}" 2>/dev/null | grep -E '^- severity: (high|blocker)' || true)
  if [ -n "$WC_OUT" ]; then
    echo "WARN: review_workflow_check.sh has high/blocker findings for stage ${N}:" >&2
    echo "$WC_OUT" >&2
    echo "(Not blocking; fix in follow-up commit if warranted.)" >&2
  fi
fi

exit 0
HOOK
chmod +x "$COMMIT_MSG_HOOK"

# ── pre-commit hook: versioned staged-addition guard ────────────────────────

if [ -e "$PRE_COMMIT_HOOK" ] && ! cmp -s "$VERSIONED_PRE_COMMIT" "$PRE_COMMIT_HOOK"; then
  PRE_COMMIT_BACKUP="${PRE_COMMIT_HOOK}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp -p "$PRE_COMMIT_HOOK" "$PRE_COMMIT_BACKUP"
  echo "Backed up existing pre-commit hook: ${PRE_COMMIT_BACKUP}"
fi
install -m 755 "$VERSIONED_PRE_COMMIT" "$PRE_COMMIT_HOOK"

# ── pre-push hook: packaging allowlist guard ───────────────────────────────

if [ -e "$PRE_PUSH_HOOK" ]; then
  PRE_PUSH_BACKUP="${PRE_PUSH_HOOK}.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp -p "$PRE_PUSH_HOOK" "$PRE_PUSH_BACKUP"
  echo "Backed up existing pre-push hook: ${PRE_PUSH_BACKUP}"
fi

cat > "$PRE_PUSH_HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh (stage 238.2).
# Blocks pushes when a flat runtime module is missing from Hatch's wheel allowlist.

set -eu

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

# Git supplies pushed refs on stdin. The test needs no refs, so detach the
# container explicitly: Docker must not consume the hook protocol stream.
exec docker compose --profile test run --rm -T test pytest -q tests/test_packaging_metadata.py < /dev/null
HOOK
chmod +x "$PRE_PUSH_HOOK"

echo "Installed hooks:"
echo "  ${COMMIT_MSG_HOOK}"
echo "  ${PRE_COMMIT_HOOK}"
echo "  ${PRE_PUSH_HOOK}"
echo ""
echo "Uninstall: rm .git/hooks/commit-msg .git/hooks/pre-commit .git/hooks/pre-push"
