#!/usr/bin/env bash
# One-shot installer for repo-local git hooks (stage 104.2).
#
# Installs hooks into .git/hooks/ with the project's workflow-discipline
# policy. Operator-controlled (run manually after clone); not auto-installed.
#
# Usage:
#   ./scripts/install_git_hooks.sh

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
HOOK_DIR="${ROOT}/.git/hooks"
if [ ! -d "$HOOK_DIR" ]; then
  echo "ERROR: .git/hooks/ not found — are you in the repo root?" >&2
  exit 1
fi

COMMIT_MSG_HOOK="${HOOK_DIR}/commit-msg"
PRE_COMMIT_HOOK="${HOOK_DIR}/pre-commit"

# ── commit-msg hook: enforces 'Stage N: ...' + AssumptionLog section ───────

cat > "$COMMIT_MSG_HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh (stage 104.2).
# Blocks commits with 'Stage N:' prefix if AssumptionLog.md has no '## Этап N' section.

set -eu

MSG_FILE="$1"
FIRST_LINE=$(head -1 "$MSG_FILE" 2>/dev/null || echo "")

# Extract N from "Stage N:" or "Stage N." prefix (case-insensitive).
N=$(echo "$FIRST_LINE" | grep -oiE '^stage [0-9]+[.:]' | grep -oE '[0-9]+' | head -1 || true)
if [ -z "$N" ]; then
  # Not a stage commit — no enforcement
  exit 0
fi

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

# 1. AssumptionLog section for stage N (accept 'Этап N', 'Этап N.', 'Этап N–M')
if ! grep -qE "^## Этап ${N}([^0-9]|\$)" AssumptionLog.md 2>/dev/null; then
  echo "ERROR: commit message is 'Stage ${N}: ...' but AssumptionLog.md has no '## Этап ${N}' section." >&2
  echo "CLAUDE.md §6 requires an AssumptionLog entry as completion criterion." >&2
  echo "" >&2
  echo "Either:" >&2
  echo "  1. Add '## Этап ${N}. <title>' section to AssumptionLog.md and re-stage it" >&2
  echo "  2. Or adjust commit message if this is not a stage commit" >&2
  echo "  3. Or bypass with 'git commit --no-verify' (not recommended)" >&2
  exit 1
fi

# 2. Non-blocking warnings from workflow-check
if [ -x scripts/review_workflow_check.sh ]; then
  WC_OUT=$(./scripts/review_workflow_check.sh "${N}" 2>/dev/null | grep -E '^- severity: (high|blocker)' || true)
  if [ -n "$WC_OUT" ]; then
    echo "WARN: review_workflow_check.sh has high/blocker findings for stage ${N}:" >&2
    echo "$WC_OUT" >&2
    echo "(Not blocking; fix in follow-up commit if warranted.)" >&2
  fi
fi

exit 0
HOOK
chmod +x "$COMMIT_MSG_HOOK"

# ── pre-commit hook: lint_api_contracts.py guard ───────────────────────────

cat > "$PRE_COMMIT_HOOK" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_git_hooks.sh (stage 104.2).
# Runs lint_api_contracts.py on staged .py files under tools/ or prompts.py.
# Blocks commit on high/blocker findings (phantom fields, phantom enum values).

set -eu

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

# Only lint staged Python files that could contain VM payloads/filters.
STAGED=$(git diff --cached --name-only --diff-filter=ACMR -- 'tools/*.py' 'prompts.py' 2>/dev/null || true)
if [ -z "$STAGED" ]; then
  exit 0
fi

FILES_ARG=$(echo "$STAGED" | tr '\n' ',' | sed 's/,$//')
if ! python3 scripts/lint_api_contracts.py --files "$FILES_ARG" >/tmp/_lint_out 2>&1; then
  echo "ERROR: lint_api_contracts.py found high/blocker findings:" >&2
  cat /tmp/_lint_out >&2
  echo "" >&2
  echo "Fix phantom fields/enum values or bypass with 'git commit --no-verify' (not recommended)." >&2
  exit 1
fi
if [ -s /tmp/_lint_out ]; then
  echo "WARN: lint_api_contracts.py found medium/low findings (not blocking):" >&2
  cat /tmp/_lint_out >&2
fi

exit 0
HOOK
chmod +x "$PRE_COMMIT_HOOK"

echo "Installed hooks:"
echo "  ${COMMIT_MSG_HOOK}"
echo "  ${PRE_COMMIT_HOOK}"
echo ""
echo "Uninstall: rm .git/hooks/commit-msg .git/hooks/pre-commit"
